#!/usr/bin/python3

from argparse import ArgumentParser
import sys
import json
import mime_counter

Hosts = dict()

def print_to_stderr(*a):
    print(*a, file = sys.stderr)

def print_csv_line(args, arr):
    s = '"'+args.outsep+'"'
    print('"'+s.join(arr)+'"')

def print_header(args):
    keys = sorted(mime_counter.as_dict(mime_counter.init_counter()).keys())
    print_csv_line(args, ['Domain','Year'] + keys)

def processFile(args, filename):
    keys = sorted(mime_counter.as_dict(mime_counter.init_counter()).keys())
    f = open(filename, 'r', errors="ignore")
    for line in f:
        p = line.find(" {\"")
        host = line[0:p]
        entry = json.loads(line[p+1:])
        for year, values in entry.items():
            out = [host, year]
            for k in keys:
                if k in values:
                    out.append(str(values[k]))
                else:
                    out.append('0')
            print_csv_line(args, out)

def dowork(args):
    if not args.noheader:
        print_header(args)
    for f in args.file:
        try:
            processFile(args, f)
        except Exception as inst:
            print_to_stderr("Error", inst, f)

parser = ArgumentParser(description='Transform summary files generated by cdx-summary.py and combine-summary.py into CSV')
parser.add_argument('-outsep', default=',', help='output field separator (default is comma)')
parser.add_argument('-fields', default='', help='output fields')
parser.add_argument('-noheader', action="store_true", help='No header in CSV file')
parser.add_argument('file', nargs='*', help='summary file (can be several)')

args = parser.parse_args()
dowork(args)
